FROM ds-hub.gree.com/docker.io/library/alpine:3.21.3
ENV LANG=en_US.UTF-8
LABEL maintainer="cynen"

# COPY analysis-stconvert/.  /plugins/analysis-stconvert/
COPY analysis-ik/.  /plugins/analysis-ik/

WORKDIR /
