FROM ds-hub.gree.com/docker.io/library/debian:12.14-slim
ENV LANG en_US.UTF-8
MAINTAINER gree


RUN set -x \
    && sed -i 's/dl-cdn.alpinelinux.org/mirror.gree.com/g' /etc/apk/repositories \
    && apk add --no-cache openjdk21 tini busybox-extras bash  tzdata curl \
    && cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
    && echo "Asia/Shanghai" > /etc/timezone
