
FROM ds-hub.gree.com/docker.io/library/alpine:3.23.5
ENV LANG=en_US.UTF-8
LABEL maintainer="gree"

COPY skywalking-agent /usr/local/agent

RUN set -x \
    && sed -i 's/dl-cdn.alpinelinux.org/mirror.gree.com/g' /etc/apk/repositories \
    && apk add --no-cache openjdk25 tini busybox-extras bash  tzdata curl \
    && cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
    && echo "Asia/Shanghai" > /etc/timezone

WORKDIR /
