
FROM ds-hub.gree.com/docker.io/library/alpine:3.21.3
ENV LANG=en_US.UTF-8
LABEL MAINTAINER=gree
RUN set -x \
    && sed -i 's/dl-cdn.alpinelinux.org/tuna.gree.com/g' /etc/apk/repositories \
    && apk add --no-cache openjdk21 tini busybox-extras bash  tzdata curl fontconfig mkfontscale font-dejavu  \
    && cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
    && echo "Asia/Shanghai" > /etc/timezone

COPY fzhtjt.TTF /usr/share/fonts/dejavu/
